- hosts: localhost
  tasks:
    - name: Run the below script
      local_action: command sh files/mysql-passbolt-backup.sh

    - name: send completion alert
      include_tasks: playbooks/send_comp_alert.yml
      tags: always
      when:
        - task_failed is not defined