- name: Send notify to Telegram
  community.general.telegram:
    token: "{{ telegram_token }}"
    api_args:
      chat_id: "{{ telegram_chat_id }}"
      parse_mode: "markdown"
      text: "✔️  Passbolt Database Backup Finished *{{inventory_hostname}}*"
      disable_web_page_preview: false
      disable_notification: false

- name: send completion notification to Discord
  tags: always
  community.general.discord:
    webhook_id: "{{discord_id}}"
    webhook_token: "{{discord_token}}"
    content: "✔️ Passbolt Database Backup Finished *{{inventory_hostname}}*"
  changed_when: False